# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
# See: https://circleci.com/docs/2.0/orb-intro/
orbs:
  ruby: circleci/ruby@0.1.2
  heroku: circleci/heroku@0.0.10
# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    parallelism: 1
    docker:
      - image: circleci/ruby:2.7.2
      # - image: circleci/ruby:2.6.3-stretch-node
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: future_seeds_api_test
    environment:
      BUNDLE_PATH: vendor/bundle
      BUNDLE_JOBS: 3
      BUNDLE_RETRY: 3
      PGHOST: 127.0.0.1
      PGUSER: postgres
      RAILS_ENV: test
    executor: ruby/default
    steps:
      - checkout
      - run:
          name: Which bundler?
          command: bundle -v

      - ruby/bundle-install
      - run:
          name: Run Test Suite
          command: bundle exec rspec -fd
# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  heroku_deploy:
    jobs:
      - build
      - heroku/deploy-via-git: # Use the pre-configured job, deploy-via-git
          app-name: $HEROKU_APP_NAME
          requires:
            - build
          filters:
            branches:
              only: main
        # post-steps:
        #   - run: heroku run rails db:migrate --app future-seeds-api
